### ISSUE TITLE
Remote - SSH extension is not worked 

### ISSUE THREAD

**Issue by clssw1004** [futurejones/code-oss-aarch64#1]
I tried several version of vscode community distrubutions,does any one know why;
OS : Ubuntu mate 20.04
Equip : Raspberry Pi 4b

**Comment by futurejones** [comment]
Unfortunately the [VS Code Remote Development Tools](https://code.visualstudio.com/docs/remote/remote-overview) are closed source and the license states that you can only use it with official Microsoft products. This means they will only work with the official release of VS Code from Microsoft.
