### ISSUE TITLE
E: unable to locate package code-oss

### ISSUE THREAD

**Issue by BennyThePythonCoder** [futurejones/code-oss-aarch64#2]
When I type `sudo apt-get install code-oss` the terminal returns `E: unable to locate package code-oss` I think I have to run `sudo apt-get update` beforehand. In the README, it doesn't say to update. I think the README should be updated so you update the os before installing code-oss.

**Comment by futurejones** [comment]
@BennyThePythonCoder The install script `curl -s https://packagecloud.io/install/repositories/swift-arm/vscode/script.deb.sh | sudo bash` to add the vscode repository includes `sudo apt-get update` and is run automatically.
If you are getting the error `E: unable to locate package code-oss` then it means there is no install package available for the OS or system you are running.
Install packages are available for Aarch64/arm64 systems running:-
Debian 10 Buster
Ubuntu 18.04 Bionic
Ubuntu 20.04 Focal

**Comment by BennyThePythonCoder** [comment]
I figured it out now 😀
